In [1]:
import torch 
import torch.nn as nn
import numpy as np
import torchvision

In [5]:
torch.cuda.is_available()

True

In [7]:
torch.__version__

'1.2.0'

In [9]:
torchvision.__version__

'0.4.0'

In [46]:
device = torch.device("cuda")

# example1

In [47]:
# Create tensor
x = torch.tensor(1.0, requires_grad=True,device=device)
w = torch.tensor(2., requires_grad=True,device=device)
b = torch.tensor(3.0, requires_grad=True,device=device)

# Build a computational graph.
y = w * x + b

y.backward()

print(x.grad) # w=2

print(w.grad) # x=1

print(b.grad) # 1

In [125]:
x = torch.randn(10, 3)

In [126]:
x

tensor([[-1.6590, -0.6640,  0.9059],
        [ 0.6537,  0.1088,  0.1715],
        [-0.4724, -0.8791,  0.0317],
        [ 0.2463, -0.9031,  0.2811],
        [-0.1270, -1.0138,  2.2483],
        [ 0.1030,  1.5687,  0.7349],
        [-0.7635, -1.0224, -0.5655],
        [-0.6109,  0.3483, -0.8885],
        [ 1.2519, -0.9542,  0.9163],
        [ 0.2900, -0.6414, -0.6923]])

In [127]:
y = torch.randn(10,2)

In [128]:
y

tensor([[ 1.5443,  1.5862],
        [-2.8739,  0.3357],
        [ 1.2960,  0.4831],
        [-0.7052, -2.0573],
        [-0.0367, -1.8619],
        [ 1.1510, -2.2753],
        [ 1.0049,  0.6595],
        [-1.5447,  1.1559],
        [-0.1159, -1.6331],
        [-0.3866,  0.2123]])

In [129]:
liner = nn.Linear(3,2)

In [130]:
liner

Linear(in_features=3, out_features=2, bias=True)

In [131]:
liner.weight

Parameter containing:
tensor([[-0.4282, -0.0086, -0.4158],
        [ 0.4865,  0.4136, -0.1423]], requires_grad=True)

In [132]:
liner.bias

Parameter containing:
tensor([-0.3034,  0.5723], requires_grad=True)

In [133]:
criterion = nn.MSELoss()

In [134]:
optimizer = torch.optim.SGD(liner.parameters(),lr=0.01)

In [135]:
pred = liner(x)

In [136]:
loss = criterion(pred,y)

In [137]:
loss

tensor(2.5489, grad_fn=<MseLossBackward>)

In [138]:
loss.item()

2.548924207687378

In [139]:
loss.backward()

In [143]:
print(liner.)

<bound method Module.train of Linear(in_features=3, out_features=2, bias=True)>


In [109]:
print(liner.weight.grad)

tensor([[-0.7320, -0.5656, -0.7325],
        [-0.0763,  0.8511, -0.4213]])


In [110]:
print(liner.bias.grad)

tensor([0.4110, 0.0979])


In [120]:
optimizer.step()

In [121]:
pred = liner(x)

In [122]:
loss = criterion(pred,y)

In [123]:
loss

tensor(1.7558, grad_fn=<MseLossBackward>)

In [124]:
loss.item()

1.7557514905929565

In [92]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

w:  Parameter containing:
tensor([[ 0.4614, -0.3480,  0.1758],
        [-0.3958,  0.1119,  0.0320]], requires_grad=True)
b:  Parameter containing:
tensor([-0.5721, -0.3114], requires_grad=True)
loss:  1.2860803604125977
dL/dw:  tensor([[-0.0322, -0.5308, -0.2040],
        [-0.2731,  0.5888,  0.6343]])
dL/db:  tensor([-0.4336, -0.8668])
loss after 1 step optimization:  1.2653443813323975


In [144]:
x = np.array([[1,2], [3,4]])

In [153]:
y = torch.from_numpy(x).cuda()

In [154]:
z = y.numpy()

TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [155]:
x

array([[1, 2],
       [3, 4]])

In [156]:
y

tensor([[1, 2],
        [3, 4]], device='cuda:0', dtype=torch.int32)

In [157]:
z

array([[1, 2],
       [3, 4]])

In [152]:
y = torch.cuda(y)

TypeError: 'module' object is not callable