In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms

In [2]:
# Hyper-parameters  超参数
input_size = 28 * 28    # 784
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

In [3]:
train_dataset = torchvision.datasets.MNIST(root="./data",
                                          train=True,
                                          transform=transforms.ToTensor(),
                                          download=True)

test_dataset = torchvision.datasets.MNIST(root="./data",
                                   train=True,
                                   transform=transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                          batch_size=batch_size,
                                          shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                         batch_size=batch_size,
                                         shuffle=False)

model = nn.Linear(input_size, num_classes)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Reshape images to (batch_size, input_size)
        images = images.reshape(-1, input_size)
        
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
        

Epoch [1/5], Step [100/600], Loss: 2.2552
Epoch [1/5], Step [200/600], Loss: 2.1307
Epoch [1/5], Step [300/600], Loss: 2.0324
Epoch [1/5], Step [400/600], Loss: 1.9922
Epoch [1/5], Step [500/600], Loss: 1.9116
Epoch [1/5], Step [600/600], Loss: 1.7871
Epoch [2/5], Step [100/600], Loss: 1.7424
Epoch [2/5], Step [200/600], Loss: 1.6878
Epoch [2/5], Step [300/600], Loss: 1.6055
Epoch [2/5], Step [400/600], Loss: 1.5872
Epoch [2/5], Step [500/600], Loss: 1.5331
Epoch [2/5], Step [600/600], Loss: 1.5416
Epoch [3/5], Step [100/600], Loss: 1.4490
Epoch [3/5], Step [200/600], Loss: 1.3518
Epoch [3/5], Step [300/600], Loss: 1.3198
Epoch [3/5], Step [400/600], Loss: 1.3330
Epoch [3/5], Step [500/600], Loss: 1.2978
Epoch [3/5], Step [600/600], Loss: 1.2447
Epoch [4/5], Step [100/600], Loss: 1.2950
Epoch [4/5], Step [200/600], Loss: 1.1571
Epoch [4/5], Step [300/600], Loss: 1.1884
Epoch [4/5], Step [400/600], Loss: 1.1015
Epoch [4/5], Step [500/600], Loss: 1.1927
Epoch [4/5], Step [600/600], Loss:

In [4]:
correct = 0 # 用于记录正确的个数
total = 0 # 记录总的个数
for images, labels in test_loader:
    images = images.reshape(-1,input_size)
    outputs = model(images)
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum()
    
print('Accuracy of the model on the 10000 test images: {} %'.format(100.0 * correct / total))

Accuracy of the model on the 10000 test images: 81.9566650390625 %


In [29]:
train_dataset[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [26]:
import pandas as pd
data = pd.read_csv("./watermelon3.0α.txt")
# 将标签进行编码
data["好瓜"] = data["好瓜"].apply(lambda x: 1 if x=="是" else 0)

data = data.values

# x.shape=(17*2)
x = data[:, 1:3]

# y.shape=(17*1)
y = data[:, 3]

x = x.astype("float32")
y = y.astype("float32")
# y = y.reshape(1,-1).T

from sklearn import model_selection
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.5, random_state=1108)
# x_train = x_train.astype("float32")
# x_test = x_test.astype("float32")
# y_train = y_train.astype("int")
# y_test = y_test.astype("int")

model_watermelon = nn.Linear(2,1)

# 交叉熵损失函数
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_watermelon.parameters(),lr=0.01)

for epoch in range(num_epochs):
    inputs = torch.from_numpy(x)
    labels = torch.from_numpy(y)
    inputs = inputs.reshape(-1,2)
        
    outputs = model_watermelon(inputs)
    loss = criterion(outputs, labels.long())
        
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
        
    if (i+1) % 100 == 0:
        print ('Loss: {:.4f}'.format(loss.item()))


IndexError: Target 1 is out of bounds.

In [24]:
torch.cuda.is_available()

True

In [11]:
y_train

array([[0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.]], dtype=float32)

In [12]:
(x_train, y_train)

(array([[0.593, 0.042],
        [0.556, 0.215],
        [0.403, 0.237],
        [0.666, 0.091],
        [0.657, 0.198],
        [0.343, 0.099],
        [0.608, 0.318],
        [0.481, 0.149]], dtype=float32),
 array([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]], dtype=float32))

In [16]:
enumerate((x_train, y_train))

In [30]:
for (features, labels) in enumerate([x, y]):
    print(features)
    print(labels)

0
[[0.697 0.46 ]
 [0.774 0.376]
 [0.634 0.264]
 [0.608 0.318]
 [0.556 0.215]
 [0.403 0.237]
 [0.481 0.149]
 [0.437 0.211]
 [0.666 0.091]
 [0.243 0.267]
 [0.245 0.057]
 [0.343 0.099]
 [0.639 0.161]
 [0.657 0.198]
 [0.36  0.37 ]
 [0.593 0.042]
 [0.719 0.103]]
1
[1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(array([[0.697, 0.46 ],
        [0.774, 0.376],
        [0.634, 0.264],
        [0.608, 0.318],
        [0.556, 0.215],
        [0.403, 0.237],
        [0.481, 0.149],
        [0.437, 0.211],
        [0.666, 0.091],
        [0.243, 0.267],
        [0.245, 0.057],
        [0.343, 0.099],
        [0.639, 0.161],
        [0.657, 0.198],
        [0.36 , 0.37 ],
        [0.593, 0.042],
        [0.719, 0.103]], dtype=float32),
 array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32))